name: Vue app deployment

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3
              with:
                token: ${{ secrets.GH_TOKEN }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Build the dist
              run: |
                  npm ci
                  npm run build --if-present
            - name: Commit build to gp-vue
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git --work-tree dist add --all 
                  git commit -m "Vue deployment run by github-actions"
                  git push origin HEAD:gp-vue --force
              shell: bash
